#!/bin/bash

#This will display the hostname, os and uptime

myHostName=$(hostname)
source /etc/os-release
os=$(PRETTY_NAME)
uptime=$(uptime)


#This will display the hardware information

cpu=$(lscpu | grep "Model name")
curSpeed=$(cat /proc/cpuinfo | grep "MHz")
maxSpeed=$(cat /proc/cpuinfo | grep "cache size")
ram=$(free -h)
disk=$(lsblk | egrep "sda|sdb")
video=$(lspci | grep VGA)

#This will display network information

fqdn=$(hostname --fqdn)
hostAdd=$(hostname -I)
gateway=$(ip route | grep default)
dnsServ=$(cat /etc/resolv.conf | grep "nameserver")

interfaceName=$(inxi -N)
ipAddCidr=$(ifconfig | grep -i mask)


#This will display system status

usersLoggedIn=$(who)
diskSpace=$(df -h)
processCount=$(ps)
loadAvr=$(cat /proc/loadavg)
memAllowFree=$(cat /proc/meminfo | grep MemFree)
listeningPorts=$(netstat -tulpn | grep LISTEN)
ufwRules=$(ufw enable | ufw status)



cat  <<EOF


System Report generated by:  $USER, $(date)


System Information
 
*******************************************************************

Hostname:	$myHostName
OS:		$PRETTY_NAME
Uptime:		$uptime


Hardware Information

*******************************************************************

Cpu:		$cpu
Speed:		$curSpeed	$maxSpeed
Ram:		$ram 
Disk(s):	$disk
Video:		$video

Network Information

******************************************************************

FQDN:		$fqdn 
Host Address:	$hostAdd
Gateway IP: 	$gateway
DNS Server:	$dnsServ

InterfaceName:	$interfaceName 
IP Address:	$ipAddCidr 


System Status

*****************************************************************

Users Logged In:	$usersLoggedIn 
Disk Space:		$diskSpace 
Process Count:		$processCount 
Load Averages:		$loadAvr 
Memory Allocation:	$memAllowFree 
Listening Network Ports:$listeningPorts
UFW Rules:		$ufwRules 

EOF
