#!/bin/bash

#This will display the hostname, os and uptime

myhostname=$(hostname)
source /etc/os-release
os=$(PRETTY_NAME)
uptime=$(uptime)


#This will display the hardware information

cpu=$(lscpu | grep "Model name")
curspeed=$(cat /proc/cpuinfo | grep "MHz")
maxspeed=$(cat /proc/cpuinfo | grep "cache size")
ram=$(free -h)
disk=$(lsblk | egrep "sda|sdb")
video=$(lspci | grep VGA)

#This will display network information

fqdn=$(hostname --fqdn)
hostadd=$(hostname -I)
gateway
dnsser

interfacename
ipaddress

#This will display system status

usersLogIn
diskspace
processcount
loadavr
memallocation
listennetports
ufwrules



cat  <<EOF


System Report generated by:  $USER, $(date)


System Information
 
*******************************************************************

Hostname:	$myhostname
OS:		$PRETTY_NAME
Uptime:		$uptime


#This will display the hardware information

Hardware Information

*******************************************************************

Cpu:		$cpu
Speed:		$curspeed	$maxspeed
Ram:		$ram 
Disk(s):	$disk
Video:		$video

#This will display the network information

Network Information

******************************************************************

FQDN:		$fqdn 
Host Address:	$hostadd
Gateway IP: 
DNS Server: 

InterfaceName: 
IP Address: 


#This will display the system status

System Status

*****************************************************************

Users Logged In: 
Disk Space: 
Process Count: 
Load Averages: 
Memory Allocation: 
Listening Network Ports: 
UFW Rules: 

EOF
